# Generated by Django 4.0.4 on 2022-05-26 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=12)),
                ('IsActive', models.BooleanField(default=False)),
                ('DateCreate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Master',
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'UserType',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.CharField(max_length=20)),
                ('Firstname', models.CharField(default='', max_length=30)),
                ('Lastname', models.CharField(default='', max_length=30)),
                ('Address', models.TextField(default='', max_length=100)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6)),
                ('City', models.CharField(default='', max_length=30)),
                ('Country', models.CharField(default='', max_length=30)),
                ('Mobile', models.CharField(default='', max_length=10)),
                ('Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocietyApp.master')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProfileImage', models.FileField(default='default.png', upload_to='profile/')),
                ('FullName', models.CharField(default='', max_length=30)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6)),
                ('Mobile', models.CharField(default='', max_length=10)),
                ('Address', models.TextField(default='', max_length=100)),
                ('Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocietyApp.master')),
            ],
            options={
                'db_table': 'Profile',
            },
        ),
        migrations.AddField(
            model_name='master',
            name='UserType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocietyApp.usertype'),
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('DateCreated', models.DateTimeField(auto_now_add=True)),
                ('LastUpdated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocietyApp.category')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocietyApp.user')),
            ],
            options={
                'db_table': 'complain',
            },
        ),
    ]
