# Generated by Django 4.0.4 on 2022-05-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApp', '0002_alter_category_table_alter_complain_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='LastUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='DateCreated',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='LastUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='complain',
            table='complain',
        ),
        migrations.AlterModelTable(
            name='master',
            table='master',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
