# Generated by Django 4.0.4 on 2022-05-27 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApp', '0003_master_lastupdated_user_datecreated_user_lastupdated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='master',
            old_name='DateCreate',
            new_name='DateCreated',
        ),
    ]
