# Generated by Django 4.0.4 on 2022-06-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApp', '0004_rename_datecreate_master_datecreated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complain',
            name='Category',
        ),
        migrations.AddField(
            model_name='complain',
            name='Complain',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
