# Generated by Django 4.0.4 on 2022-06-15 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApp', '0005_remove_complain_category_complain_complain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Society_rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Society_rules', models.TextField(default='', max_length=100)),
                ('DateCreated', models.DateTimeField(auto_now_add=True)),
                ('LastUpdated', models.DateTimeField(auto_now=True)),
                ('Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocietyApp.master')),
            ],
            options={
                'db_table': 'society_rules',
            },
        ),
    ]
