# Generated by Django 4.0.4 on 2022-06-15 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApp', '0007_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eventname', models.CharField(max_length=50)),
                ('EventImage', models.FileField(default='default.jpg', upload_to='event/')),
                ('Eventdescription', models.TextField(default='', max_length=100)),
                ('DateCreated', models.DateTimeField(auto_now_add=True)),
                ('LastUpdated', models.DateTimeField(auto_now=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocietyApp.user')),
            ],
            options={
                'db_table': 'event',
            },
        ),
    ]
